## PyTorch is Just numpy on GPUs

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jonathandinu/youtube/blob/main/notebooks/pytorch-intro.ipynb) [![YouTube Video Views](https://img.shields.io/youtube/views/Eaqb_fD7pZw)](https://youtu.be/Eaqb_fD7pZw) [![GitHub Repo stars](https://img.shields.io/github/stars/jonathandinu/youtube?style=social)](https://github.com/jonathandinu/youtube)

> Colab for interactive execution in your browser (no setup) and repository for notebook index and additional resources/code.

## References and Resources

* Pytorch Homepage: https://pytorch.org/
* PyTorch API Docs: https://docs.pytorch.org/docs/stable/
* PyTorch Tutorials: https://docs.pytorch.org/tutorials/
* PyTorch Recipes: https://docs.pytorch.org/tutorials/re...
* Tensor Creation Ops: https://docs.pytorch.org/docs/stable/...
* Lua Torch Homepage: http://torch.ch/

In [82]:
import torch

In [84]:
x = torch.Tensor([1,2,3])

In [89]:
x.double()

tensor([1., 2., 3.], dtype=torch.float64)

In [94]:
x = torch.ones(10)

In [106]:
x = torch.arange(10).reshape((2, 5))

In [107]:
print(f"x is a rank {len(x.shape)} tensor.")

x is a rank 2 tensor.


In [109]:
x.numpy()

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [112]:
torch.mps.is_available()

False

In [113]:
x.device

device(type='cpu')

In [116]:
x.to('cuda')#.to('cpu')

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]], device='cuda:0')

In [118]:
x = x.to('cuda')

In [119]:
x.device

device(type='cuda', index=0)

In [122]:
x.cpu() + torch.arange(10).reshape((2, 5))

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]])

In [124]:
x.to('cpu')

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [125]:
x.cuda()

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]], device='cuda:0')

## Appendix

In [1]:
# version of Python of the current Jupyter kernel
import sys, datetime

print(f"Current notebook Python version: {sys.version}")
print(f"Notebook last executed: {datetime.datetime.now()}")

# package versions when this notebook was last run (and committed)
!pip freeze

Current notebook Python version: 3.12.8 (main, Jan 14 2025, 22:49:14) [Clang 19.1.6 ]
Notebook last executed: 2025-05-06 16:34:59.060508
aiohttp==3.8.3
aiosignal==1.3.1
asgiref==3.5.2
asttokens==3.0.0
async-generator==1.10
async-timeout==4.0.2
attrs==22.2.0
Automat==20.2.0
Babel==2.8.0
bcrypt==3.2.0
blinker==1.4
boto==2.49.0
botocore==1.29.43
certifi==2021.10.8
chardet==4.0.0
charset-normalizer==2.0.12
click==8.0.3
cloud-init==24.3.1
colorama==0.4.4
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
contourpy==1.3.1
cryptography==3.4.8
cycler==0.11.0
dbus-python==1.2.18
decorator==5.1.1
distro==1.7.0
distro-info==1.1+ubuntu0.2
dj-database-url==0.5.0
Django==2.2
django-cors-headers==2.5.3
django-storages-redux==1.3.3
exceptiongroup==1.1.0
executing==2.2.0
fonttools==4.56.0
frozenlist==1.3.3
gensim==3.8.0
git-filter-repo==2.34.0
gunicorn==20.1.0
gyp==0.1
h11==0.14.0
httplib2==0.20.2
hyperlink==21.0.0
idna==3.3
importlib-metadata==4.8.2
incremental==21.3.0
ipdb==0.13.13
ipython==8